In [10]:
import os
import random
import numpy as np
from keras.preprocessing.image import ImageDataGenerator

class InfiniteDataLoader:
    def __init__(self, data_dir, batch_size, target_size=(224, 224), shuffle=True):
        """
        Constructer.

        Args:
            data_dir: dataset Path.
            batch_size: batch_size.
            target_size: image size.
            shuffle: shuffle.
        """
        self.data_dir = data_dir
        self.batch_size = batch_size
        self.target_size = target_size
        self.shuffle = shuffle
        self.classes = sorted(os.listdir(data_dir))
        self.num_classes = len(self.classes) # folder count to count classes
#         print(self.num_classes)
        self.image_data_generator = ImageDataGenerator() #keras function
        self.image_generator = self.image_data_generator.flow_from_directory(
            data_dir,
            target_size=target_size,
            batch_size=batch_size,
            class_mode='categorical',
            shuffle=shuffle
        )

    def __iter__(self): # to get all batch at once
        return self

    def __next__(self): # to get on by on batch
        images, labels = next(self.image_generator)
        return images, labels


In [13]:
# Example usage:
data_dir = 'train/train/'
batch_size = 8

data_loader = InfiniteDataLoader(data_dir, batch_size)

# Iterate and get batches of images infinitely
for i in range(10):  # example: iterate for 10 batches
    images, labels = next(data_loader)
    print(f"Batch {i+1}:")
    print(images.shape, labels)

3
Found 1034 images belonging to 3 classes.
Batch 1:
(5, 224, 224, 3) [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
Batch 2:
(5, 224, 224, 3) [[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Batch 3:
(5, 224, 224, 3) [[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Batch 4:
(5, 224, 224, 3) [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Batch 5:
(5, 224, 224, 3) [[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
Batch 6:
(5, 224, 224, 3) [[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
Batch 7:
(5, 224, 224, 3) [[1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Batch 8:
(5, 224, 224, 3) [[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Batch 9:
(5, 224, 224, 3) [[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
Batch 10:
(5, 224, 224, 3) [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]


In [9]:
next(data_loader)

(array([[[[ 47.,  31.,  15.],
          [ 55.,  40.,  21.],
          [ 59.,  44.,  23.],
          ...,
          [ 22.,  17.,  13.],
          [ 21.,  18.,  13.],
          [ 22.,  19.,  14.]],
 
         [[ 77.,  61.,  38.],
          [ 85.,  69.,  44.],
          [ 95.,  78.,  52.],
          ...,
          [ 27.,  20.,  14.],
          [ 23.,  18.,  14.],
          [ 23.,  18.,  14.]],
 
         [[ 99.,  80.,  48.],
          [ 98.,  79.,  47.],
          [101.,  82.,  50.],
          ...,
          [ 29.,  22.,  12.],
          [ 24.,  19.,  13.],
          [ 23.,  18.,  14.]],
 
         ...,
 
         [[ 48.,  62.,  11.],
          [ 37.,  51.,   0.],
          [ 43.,  61.,  11.],
          ...,
          [ 15.,  28.,   0.],
          [ 16.,  29.,   1.],
          [ 18.,  29.,   0.]],
 
         [[ 70.,  70.,  34.],
          [ 70.,  70.,  32.],
          [ 71.,  73.,  33.],
          ...,
          [ 17.,  27.,   2.],
          [ 19.,  30.,   0.],
          [ 19.,  30.,   0.